drop table IF EXISTS bookings cascade;

drop table IF EXISTS comments cascade;

drop table IF EXISTS items cascade;

drop table IF EXISTS requests cascade;

drop table IF EXISTS users cascade;

CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DESCRIPTION TEXT,
    REQUEST_USER_ID BIGINT REFERENCES USERS(ID) ON DELETE CASCADE,
    CREATED_DATE TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME varchar(255) NOT NULL,
    DESCRIPTION TEXT,
    AVAILABLE boolean,
    OWNER_ID BIGINT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    REQUEST_ID BIGINT REFERENCES REQUESTS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BOOKINGS
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    START_DATE TIMESTAMP WITHOUT TIME ZONE,
    END_DATE TIMESTAMP WITHOUT TIME ZONE,
    ITEM_ID BIGINT NOT NULL REFERENCES ITEMS(ID) ON DELETE CASCADE,
    BOOKER_ID BIGINT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    STATUS varchar(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMMENTS
(
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXT TEXT,
    ITEM_ID BIGINT NOT NULL REFERENCES ITEMS(ID) ON DELETE CASCADE,
    AUTHOR_ID BIGINT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    CREATED_DATE TIMESTAMP WITHOUT TIME ZONE
);